[versions]
kotlin = "2.2.0"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.6.1"
kotlin-logging = "7.0.3"
bignum = "0.3.10"
shadowJar = "8.3.6"
ndkore = "1.6.1"
ornament = "1.2.0"
google-guava = "33.4.0-jre"
authlib = "1.11"
koin = "4.0.1"
nbtapi = "2.14.1"
slf4j = "2.0.16"

[libraries]
ndkore = { module = "dev.nikdekur:ndkore", version.ref = "ndkore" }
ornament = { module = "dev.nikdekur:ornament", version.ref = "ornament" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
google-guava = { module = "com.google.guava:guava", version.ref = "google-guava" }
authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadowJar" }
