rcon:
  host: "172.30.236.206"
  port: 25570
  password: "8M1LjY0lbGy6bucJX5"

#sftp:
#  host: "172.30.236.206"
#  port: 2722
#  username: "nik_de_kur.b7ee1ab9"
#  password: "bc5na9kn"

actions:
  - action: "command"
    command: "plugman unload MineLib"

  - action: "upload"
    source: "C:/codes/Java/Projects/minelib/build/libs/minelib-1.1.1.jar"
    destination: "//wsl.localhost/Ubuntu/var/lib/pterodactyl/volumes/8911ca59-edd7-42de-bf61-f5326ede0422/plugins/minelib-1.1.1.jar"

  - action: "command"
    command: "plugman load MineLib"